import SearchInput from "./c/SearchInput";
import Head from "next/head";
import React from "react";
import categories from "@data/category";
import PostSection from "@components/AdSection";

const Home: React.FC = () => {
    const handlePageChange = (pageNumber: number) => {};

    return (
        <div className="flex justify-center pt-10 pb-20 bg-bg-primary">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="max-w-screen-md flex flex-col  w-full gap-10">
                <div className="flex gap-x-5 bg-white p-5 rounded-lg">
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500">
                        <label>APPLE</label>
                    </div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                    <div className="border-2 w-20 h-20 rounded-md transition cursor-pointer border-primary hover:bg-yellow-500"></div>
                </div>

                <div className="flex gap-x-10">
                    <div
                        className="hidden  bg-white rounded-lg p-5
                                    sm:inline-flex sm:w-64"
                    >
                        <ul>
                            {categories.map((category) => (
                                <li key={category.id}>
                                    <a className="cursor-pointer">{category.name}</a>
                                </li>
                            ))}
                        </ul>
                    </div>
                    <div className="flex flex-col gap-y-5 w-full">
                        <SearchInput />
                        <PostSection onPageChange={handlePageChange} />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;
